<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mang inasal delivery app</title>
    <link rel="stylesheet" href=<?php echo $paths['CSS_PATH'] . 'index.css';  ?>>
    <link rel="stylesheet" href=<?php echo $paths['CSS_PATH'] . 'header.css';  ?>>
    <link rel="stylesheet" href=<?php echo $paths['CSS_PATH'] . 'swipe.css';  ?>>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"
    />
</head>