<!DOCTYPE html>
<html lang="en">
<?php 
    include $paths['PARTIALS_PATH'] . 'head.phtml';
    
?>
<body>
    <?php 
        include $paths['PARTIALS_PATH'] . 'header.phtml';
      if (!isset($_SESSION['name'])) {
        ?>
          <div class="login-popup active" id="login-popup">
            <div class="login-container">
            <form method="POST" action=<?php echo $paths['CONTROLLERS_PATH'] . 'login.php'; ?>>
              <p class="not-auth">X</p>
              <h1>Login</h1>
              <div class="input-group">
                <label>
                Username
                </label> <br/>
                <input type="text" name="username">
              </div>
              <div class="input-group">
                <label>
                Password
                </label> <br/>
                <input type="text" name="password">
                </div>
              <div class="input-group">
              <input type="submit" value="Login">
              </div>
            </form>
            </div>
          </div>
          <?php
          }    
    ?>

    <div class="swiper-container">
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <div class="swiper-slide">
                    <img src="https://lh3.googleusercontent.com/hcSOnMRTvR7r6DFYOqphCy3V3xxLAQEhGEd3wlwTGTqwBNOPhWr8mTYzHnsyqlvTg6bH3Bs8pMmtGD1ibH1gxwxkCZiValCFKgM=w1170-rw" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="https://lh3.googleusercontent.com/sIKnGNgfH7-p6TDzAiI5-RF8DxYsjvGwfTxTi_2Q9HWJ9JSpMhL6lVs0S06KpgwJ_w6qD54XUh2lTlb96HFQ59PZo7i3bV9BN2GVMA=w1170-rw" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="https://lh3.googleusercontent.com/3LbmlpwloJDjhIPU5UgLMCAkbQGY6LVWPK2ae4o2rxU5kBpoqBeq7r2f7tBk8EZBogUpQjNa_gp3ic-hOY7KvHyHnPdU0v4f-Naw=w1170-rw" alt="">
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <script src=<?php echo $paths['JS_PATH'] . 'loginPopup.js'; ?>></script>

    <script src=<?php echo $paths['JS_PATH'] . 'swiper.js' ?>></script>
</body>
</html>